actions:
  vundle: vim +VundleClean! +VundleInstall +VundleInstall! +qall
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_vundle:
    src: vim/bundle/Vundle.vim
    dst: ~/.vim/bundle/Vundle.vim
    link: link
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    link: link
    actions:
    - vundle
  d_tpm:
    src: tmux/plugins/tpm
    dst: ~/.tmux/plugins/tpm
    link: link
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    link: link
  d_p10k:
    src: config/powerlevel10k
    dst: ~/.config/powerlevel10k
    link: link
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    link: link
  f_aliases:
    src: aliases
    dst: ~/.aliases
    link: link
  f_condarc:
    src: condarc
    dst: ~/.condarc
    link: link
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
    link: link
profiles:
  Joshuas-MacBook-Pro.local:
    dotfiles:
    - d_vundle
    - f_vimrc
    - d_tpm
    - f_tmux.conf
    - d_p10k
    - f_zshrc
    - f_aliases
    - f_condarc
    - f_p10k.zsh
